# Generated by Django 4.0.6 on 2022-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjsapp', '0003_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('pwd', models.CharField(max_length=200)),
                ('phone', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('update', models.DateTimeField()),
            ],
        ),
    ]
